name: chat_gpt_flutter
description: ChatGPT API implemented in Flutter
version: 1.0.9
repository: https://github.com/hrvojecukman/chat_gpt_flutter

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.1.1
  flutter:
    sdk: flutter
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  retrofit_generator: ^6.0.0+3
  build_runner: ^2.3.3


flutter:
